name: Build and Publish JAR to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # 当 Git 标签推送时触发工作流

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 可选：temurin 是 OpenJDK 的一种
          java-version: 17

      - name: Generate version number based on Git tag
        id: version
        run: |
          VERSION=$(git describe --tags --always)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set version in gradle.properties
        run: |
          echo "version=${{ env.VERSION }}" >> gradle.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and publish to Git Hub Packages
        run: ./gradlew publish
        env:
          GPR_USER: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_REPO: ${{ github.repository }}
